apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    azure:
      secretStorage:
        keyVaultName: adapted-crane
      storage:
        storageAccountName: jxadaptedcrane
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    environmentGitOwner: Jamin-Consulting
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: aks
    registry: adaptedcrane.azurecr.io
  environments:
  - key: dev
    owner: Jamin-Consulting
    repository: jx3-azure-akv-cluster
  ingress:
    domain: 51.140.220.231.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jaminconsulting
  repository: nexus
  secretStorage: azurekeyvault
  storage:
  - name: logs
    url: azblob://logs
  vault: {}
  webhook: lighthouse
